version: '3.2'
services:
  mongo-primary:
    image: mongo:4.1.13-bionic
    command: --replSet rs0 --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: project_manager
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
  mongo-secondary:
    image: mongo:4.1.13-bionic
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    depends_on:
      - mongo-primary
  mongo-replicator:
    build: ./mongo-replicator
    networks:
      - mongo-cluster
    depends_on:
      - mongo-primary
      - mongo-secondary
networks:
  mongo-cluster:
    driver: bridge

